import { createFinding, hashObject, newId, ScanProfileSchema, type AuditManifest, type CategoryScore, type Finding, type PageSnapshot, type ScanProfile } from '@sitechronicle/core';
import type { Database } from './db.js';
import { ArtifactStore } from './artifacts.js';
import { crawlSite, type CrawledPage } from './crawler.js';
import { analyzeSeo } from './scanners/seo.js';
import { analyzeSecurity, inspectTls, runZapBaseline } from './scanners/security.js';
import { scanBrowserPage } from './scanners/browser.js';
import { runLighthouse, type LighthouseDeviceResult } from './scanners/lighthouse.js';
import { fetchCrux } from './scanners/crux.js';
import { analyzeSitewide } from './scanners/sitewide.js';
import { enrichWithAi } from './scanners/ai.js';
import { median } from './scanners/math.js';
import { config } from './config.js';

interface AuditRow { id:string;domain_id:string;status:string;manifest:AuditManifest;origin:string;hostname:string;profile_config:unknown;verified_at:string|null }
interface StoredPage { page:CrawledPage; pageId:string; htmlEvidenceId:string; headersEvidenceId:string }

export async function runAudit(database:Database,auditId:string):Promise<void>{
  const rows=await database<Array<AuditRow>>`SELECT a.id,a.domain_id,a.status,a.manifest,d.origin,d.hostname,d.verified_at,p.config AS profile_config FROM audits a JOIN domains d ON d.id=a.domain_id LEFT JOIN scan_profiles p ON p.id=a.profile_id WHERE a.id=${auditId}`;const audit=rows[0];if(!audit)throw new Error('Audit not found');if(audit.status==='cancelled')return;
  const profile=ScanProfileSchema.parse(audit.profile_config??audit.manifest.profile);const startedAt=new Date();const manifest:AuditManifest={...audit.manifest,startedAt:startedAt.toISOString(),workerId:config.workerId,profile,profileHash:hashObject(profile),scannerVersions:{ruleset:'1.0.0',playwright:'1.62.1',lighthouse:'13.4.1',axeCore:'4.12.1',zap:config.zapApiUrl?'remote-enabled':'disabled',chromium:config.chromePath??'playwright-bundled'},environment:{...audit.manifest.environment,node:process.version,platform:process.platform}};
  await database`UPDATE audits SET status='running',started_at=${startedAt},manifest=${database.json(manifest as never)},error=null WHERE id=${auditId}`;
  const store=new ArtifactStore(database);const allFindings:Finding[]=[];const warnings:string[]=[];const lighthouseResults:LighthouseDeviceResult[]=[];const browserScores:{accessibility:number;bestPractices:number}[]=[];
  try{
    const crawl=await crawlSite(audit.origin,profile,message=>console.log(`[${auditId}] ${message}`));warnings.push(...crawl.warnings);
    const robotsEvidence=await store.put({auditId,kind:'robots',mimeType:'text/plain; charset=utf-8',data:crawl.robots.text,extension:'txt',pageUrl:crawl.robots.url,metadata:{status:crawl.robots.status}});
    const sitemapEvidence=[];for(const sitemap of crawl.sitemaps)sitemapEvidence.push(await store.put({auditId,kind:'sitemap',mimeType:'application/xml',data:sitemap.text,extension:'xml',pageUrl:sitemap.url,metadata:{status:sitemap.status}}));
    if(crawl.robots.status!==200)allFindings.push(createFinding({auditId,ruleId:'SEO-ROBOTS-SITE-001',category:'seo',severity:'medium',title:'robots.txt is unavailable',observation:`robots.txt returned ${crawl.robots.status||'no response'}.`,impactHypothesis:'Crawler policy and sitemap discovery become less explicit.',impactStatus:'research-backed-hypothesis',probableCause:'The conventional robots route is missing or inaccessible.',recommendation:'Publish a valid robots.txt with a Sitemap directive.',acceptanceCriteria:['/robots.txt returns 200 text/plain','Rules are grouped under User-agent'],evidenceIds:[robotsEvidence.id],sourceUrls:['https://developers.google.com/search/docs/crawling-indexing/robots/intro'],confidence:1}));
    if(crawl.robots.text&&!/^\s*User-agent:/im.test(crawl.robots.text))allFindings.push(createFinding({auditId,ruleId:'SEO-ROBOTS-SITE-002',category:'seo',severity:'high',title:'robots.txt has no valid User-agent group',observation:'No User-agent directive was found.',impactHypothesis:'Rules outside a crawler group can be ignored or interpreted inconsistently.',impactStatus:'research-backed-hypothesis',probableCause:'robots.txt directives are emitted in the wrong order.',recommendation:'Begin each rule group with User-agent and validate the file.',acceptanceCriteria:['Parser detects at least one User-agent group','Lighthouse robots audit passes'],evidenceIds:[robotsEvidence.id],sourceUrls:['https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt'],confidence:1}));
    if(!/^[ \t]*Sitemap:/im.test(crawl.robots.text))allFindings.push(createFinding({auditId,ruleId:'SEO-ROBOTS-SITEMAP-001',category:'seo',severity:'low',title:'robots.txt does not advertise a sitemap',observation:'No Sitemap directive was found.',impactHypothesis:'Sitemap discovery relies on submission or conventional guessing.',impactStatus:'research-backed-hypothesis',probableCause:'The robots template does not include the sitemap index.',recommendation:'Add the absolute sitemap index URL.',acceptanceCriteria:['Sitemap directive is absolute','Declared sitemap returns 200'],evidenceIds:[robotsEvidence.id],sourceUrls:['https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap'],confidence:1}));

    const stored:StoredPage[]=[];
    for(const page of crawl.pages){
      if(await isCancelled(database,auditId))throw new AuditCancelledError();const pageId=newId('page');
      await database`INSERT INTO pages (id,audit_id,url,normalized_url,final_url,status_code,template,title,description,canonical,h1,language,robots,content_hash,raw_html_bytes,headers,metrics,resources) VALUES (${pageId},${auditId},${page.url},${page.normalizedUrl},${page.finalUrl},${page.statusCode},${page.template},${page.title},${page.description},${page.canonical},${database.json(page.h1 as never)},${page.language},${page.robots},${page.contentHash},${Buffer.byteLength(page.html)},${database.json(page.headers as never)},'{}'::jsonb,'[]'::jsonb) ON CONFLICT (audit_id,normalized_url) DO NOTHING`;
      const htmlEvidence=await store.put({auditId,pageId,kind:'html',mimeType:'text/html; charset=utf-8',data:page.html,extension:'html',pageUrl:page.finalUrl,metadata:{status:page.statusCode,template:page.template}});const headersEvidence=await store.put({auditId,pageId,kind:'headers',mimeType:'application/json',data:JSON.stringify(page.headers,null,2),extension:'json',pageUrl:page.finalUrl});
      const seo=analyzeSeo({auditId,pageId,page,htmlEvidenceId:htmlEvidence.id});const security=analyzeSecurity({auditId,pageId,page,headersEvidenceId:headersEvidence.id});allFindings.push(...seo.findings,...security.findings);
      await database`UPDATE pages SET metrics=${database.json({seo:seo.metrics,security:{score:security.score}} as never)} WHERE id=${pageId}`;stored.push({page,pageId,htmlEvidenceId:htmlEvidence.id,headersEvidenceId:headersEvidence.id});
    }

    const representative=selectRepresentative(stored,profile.maxBrowserPages);
    for(const item of representative){for(const device of profile.devices){if(await isCancelled(database,auditId))throw new AuditCancelledError();try{const browser=await scanBrowserPage({database,auditId,pageId:item.pageId,url:item.page.finalUrl,profile,device});allFindings.push(...browser.findings);browserScores.push({accessibility:browser.scores.accessibility??0,bestPractices:browser.scores.bestPractices??0});await mergePageMetrics(database,item.pageId,{[`browser_${device}`]:browser.metrics},browser.resources,browser.screenshotHash,browser.domHash)}catch(error){warnings.push(`Browser ${device} ${item.page.finalUrl}: ${String(error)}`)}}}
    for(const item of representative.slice(0,Math.min(5,representative.length))){for(const device of profile.devices){if(await isCancelled(database,auditId))throw new AuditCancelledError();try{const result=await runLighthouse({database,auditId,pageId:item.pageId,url:item.page.finalUrl,device,profile});lighthouseResults.push(result);await mergePageMetrics(database,item.pageId,{[`lighthouse_${device}`]:result,performance:result.metrics},result.resources)}catch(error){warnings.push(`Lighthouse ${device} ${item.page.finalUrl}: ${String(error)}`)}}}

    const sitewide=analyzeSitewide({auditId,pages:stored.map(item=>({page:item.page,evidenceId:item.htmlEvidenceId})),robotsEvidenceId:robotsEvidence.id,sitemapEvidenceIds:sitemapEvidence.map(item=>item.id)});allFindings.push(...sitewide.findings);
    try{const tls=await inspectTls(audit.origin);await store.put({auditId,kind:'tls',mimeType:'application/json',data:JSON.stringify(tls,null,2),extension:'json',pageUrl:audit.origin})}catch(error){const evidence=await store.put({auditId,kind:'tls',mimeType:'application/json',data:JSON.stringify({error:String(error)},null,2),extension:'json',pageUrl:audit.origin});allFindings.push(createFinding({auditId,ruleId:'SEC-TLS-001',category:'security',severity:'critical',title:'TLS validation failed',observation:String(error),impactHypothesis:'Users and scanners cannot establish a validated encrypted connection.',impactStatus:'measured',probableCause:'Certificate, protocol, hostname or connectivity failure.',recommendation:'Repair the certificate chain and modern TLS endpoint.',acceptanceCriteria:['TLS connection validates for the canonical hostname','Certificate is unexpired and trusted'],evidenceIds:[evidence.id],sourceUrls:['https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security'],confidence:1}))}
    if(profile.includeSecurityBaseline&&config.zapApiUrl){try{const zap=await runZapBaseline(audit.origin);if(zap){const evidence=await store.put({auditId,kind:'report',mimeType:'application/json',data:JSON.stringify(zap,null,2),extension:'json',pageUrl:audit.origin,metadata:{scanner:'zaproxy-baseline'}});const alerts=(zap.alerts as Array<Record<string,unknown>>|undefined)??[];for(const alert of alerts.slice(0,100)){const risk=String(alert.risk??'').toLowerCase();allFindings.push(createFinding({auditId,ruleId:`ZAP-${String(alert.pluginId??'UNKNOWN')}`,category:'security',severity:risk.includes('high')?'high':risk.includes('medium')?'medium':risk.includes('low')?'low':'info',title:String(alert.alert??'ZAP passive alert'),observation:String(alert.description??'Passive scanner alert.'),impactHypothesis:String(alert.riskdesc??'Security posture signal requiring validation.'),impactStatus:'site-hypothesis',probableCause:String(alert.evidence??alert.param??'See ZAP evidence.'),recommendation:String(alert.solution??'Validate and remediate the passive alert.'),acceptanceCriteria:['Alert is reproduced and triaged','False positives include written rationale'],evidenceIds:[evidence.id],sourceUrls:[String(alert.reference??'https://www.zaproxy.org/docs/docker/baseline-scan/')],confidence:.8}))}}}catch(error){warnings.push(`ZAP baseline: ${String(error)}`)}}
    let crux:null|Record<string,unknown>=null;if(profile.includeCrux){try{crux=await fetchCrux(audit.origin);if(crux)await store.put({auditId,kind:'metric',mimeType:'application/json',data:JSON.stringify(crux,null,2),extension:'json',pageUrl:audit.origin,metadata:{source:'CrUX API'}})}catch(error){warnings.push(`CrUX: ${String(error)}`)}}

    await persistFindings(database,allFindings);const ai=await enrichWithAi(allFindings).catch(error=>{warnings.push(`AI review: ${String(error)}`);return null});if(ai)for(const [findingId,review] of Object.entries(ai))await database`UPDATE findings SET payload=payload || ${database.json({aiReview:review} as never)} WHERE id=${findingId}`;
    const scores=buildScores(allFindings,lighthouseResults,browserScores,sitewide.agentScore);const completedAt=new Date();manifest.completedAt=completedAt.toISOString();
    const counts=countFindings(allFindings);await database`UPDATE audits SET status='completed',completed_at=${completedAt},manifest=${database.json(manifest as never)},scores=${database.json(scores as never)},summary=${database.json({pagesScanned:stored.length,browserPages:representative.length,performanceMeasurements:lighthouseResults.length,findings:counts,warnings,facts:sitewide.facts,cruxAvailable:Boolean(crux),durationMs:completedAt.getTime()-startedAt.getTime()} as never)} WHERE id=${auditId}`;
  }catch(error){
    // Preserve every evidence-backed finding produced before a scanner failure. A
    // failed run remains useful for diagnosis, while its status still prevents it
    // from being mistaken for a complete baseline.
    await persistFindings(database,allFindings).catch(persistError=>warnings.push(`Partial finding persistence: ${String(persistError)}`));
    if(error instanceof AuditCancelledError){await database`UPDATE audits SET status='cancelled',completed_at=now(),summary=${database.json({warnings,partialFindings:allFindings.length} as never)},error=null WHERE id=${auditId}`;return}
    await database`UPDATE audits SET status='failed',completed_at=now(),summary=${database.json({warnings,partialFindings:allFindings.length} as never)},error=${String(error instanceof Error?`${error.message}\n${error.stack??''}`:error).slice(0,20_000)} WHERE id=${auditId}`;throw error
  }
}

async function persistFindings(database:Database,findings:Finding[]):Promise<void>{for(const finding of findings)await database`INSERT INTO findings (id,audit_id,page_id,fingerprint,rule_id,category,severity,title,payload) VALUES (${finding.id},${finding.auditId},${finding.pageId??null},${finding.fingerprint},${finding.ruleId},${finding.category},${finding.severity},${finding.title},${database.json(finding as never)}) ON CONFLICT (audit_id,fingerprint) DO UPDATE SET payload=EXCLUDED.payload,severity=EXCLUDED.severity,title=EXCLUDED.title`}
async function mergePageMetrics(database:Database,pageId:string,metrics:Record<string,unknown>,resources:PageSnapshot['resources'],screenshotHash?:string,domHash?:string):Promise<void>{await database`UPDATE pages SET metrics=metrics || ${database.json(metrics as never)},resources=CASE WHEN jsonb_array_length(${database.json(resources as never)}::jsonb)>0 THEN ${database.json(resources as never)}::jsonb ELSE resources END,screenshot_hash=COALESCE(${screenshotHash??null},screenshot_hash),dom_hash=COALESCE(${domHash??null},dom_hash) WHERE id=${pageId}`}
function selectRepresentative(items:StoredPage[],limit:number):StoredPage[]{const result:StoredPage[]=[];const templates=['home','product','category','policy','content','account','cart','checkout','search','unknown'];for(const template of templates){const found=items.find(item=>item.page.template===template&&!result.includes(item));if(found)result.push(found);if(result.length>=limit)return result}for(const item of items){if(!result.includes(item))result.push(item);if(result.length>=limit)break}return result}
function buildScores(findings:Finding[],lh:LighthouseDeviceResult[],browser:Array<{accessibility:number;bestPractices:number}>,agentScore:number):CategoryScore[]{const now=new Date().toISOString();const penalty=(category:Finding['category'])=>Math.max(0,100-findings.filter(f=>f.category===category).reduce((sum,f)=>sum+({critical:25,high:12,medium:6,low:2,info:0}[f.severity]),0));const lhScore=(key:keyof LighthouseDeviceResult['scores'])=>lh.length?median(lh.map(item=>item.scores[key])):null;return[{category:'performance',score:lhScore('performance'),source:'Lighthouse median across representative profiles',measuredAt:now},{category:'seo',score:lhScore('seo')??penalty('seo'),source:lh.length?'Lighthouse median':'transparent rule penalties',measuredAt:now},{category:'accessibility',score:lhScore('accessibility')??(browser.length?median(browser.map(item=>item.accessibility)):penalty('accessibility')),source:lh.length?'Lighthouse median':'axe rule penalties',measuredAt:now},{category:'best-practices',score:lhScore('bestPractices')??(browser.length?median(browser.map(item=>item.bestPractices)):penalty('best-practices')),source:lh.length?'Lighthouse median':'browser rule penalties',measuredAt:now},{category:'security',score:penalty('security'),source:'transparent passive security penalties',measuredAt:now},{category:'behavioral-ux',score:penalty('behavioral-ux'),source:'behavioral friction risk rules; not a psychological diagnosis',measuredAt:now},{category:'agent-readiness',score:agentScore,source:'structured entity and fact consistency coverage',measuredAt:now}]}
function countFindings(findings:Finding[]):Record<string,number>{return findings.reduce((acc,item)=>{acc[item.severity]=(acc[item.severity]??0)+1;return acc},{critical:0,high:0,medium:0,low:0,info:0} as Record<string,number>)}
async function isCancelled(database:Database,auditId:string):Promise<boolean>{const rows=await database<Array<{status:string}>>`SELECT status FROM audits WHERE id=${auditId}`;return rows[0]?.status==='cancelled'}
class AuditCancelledError extends Error{}
