import { newId, sha256 } from '@sitechronicle/core';
import { load as loadHtml } from 'cheerio';
import type { Database } from './db.js';
import type { Job } from './queue.js';
import { validateTarget } from './security/target.js';
import { assertBudget, fetchSerp, loadSerpConnector } from './connectors/serp.js';
import { decryptCredentials } from './connectors/secrets.js';

export async function runIntelligenceJob(database:Database,job:Job):Promise<void>{
  switch(job.type){
    case'connector_test':return connectorTest(database,String(job.payload.connectorId));
    case'keyword_discovery':return discoverKeywords(database,String(job.payload.domainId));
    case'serp_batch':return runSerpBatch(database,job);
    case'competitor_refresh':return refreshCompetitors(database,String(job.payload.domainId));
    case'public_performance':case'crux_refresh':case'availability_probe':return refreshPublicPerformance(database,String(job.payload.domainId));
    case'common_crawl_refresh':return refreshCommonCrawl(database,String(job.payload.domainId));
    case'experiment_evaluate':return evaluateExperiment(database,String(job.payload.experimentId));
    case'opportunity_rebuild':return rebuildRankingOpportunities(database,String(job.payload.domainId));
    case'portfolio_digest':return buildDigest(database);
    case'light_crawl':case'deep_crawl':case'lighthouse_sample':throw new Error(`${job.type} requires an audit profile and is scheduled through the audit system`);
    default:throw new Error(`Unknown job type: ${job.type}`);
  }
}

async function connectorTest(database:Database,id:string):Promise<void>{
  const rows=await database<Array<Record<string,unknown>>>`SELECT * FROM connector_configs WHERE id=${id}`;const row=rows[0];if(!row)throw new Error('Connector not found');try{if(row.provider==='dataforseo'||row.provider==='serpapi'){const connector=await loadSerpConnector(database,id);await fetchSerp(connector,{query:'sitechronicle test',location:'United States',country:'US',language:'en',device:'desktop',depth:10})}else if(row.provider==='crux'){const credentials=decryptCredentials(String(row.encrypted_credentials));const response=await fetch(`https://chromeuxreport.googleapis.com/v1/records:queryRecord?key=${encodeURIComponent(credentials.apiKey)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({origin:'https://www.google.com'}),signal:AbortSignal.timeout(20_000)});if(!response.ok&&response.status!==404)throw new Error(`CrUX ${response.status}`)}else{const response=await fetch('https://index.commoncrawl.org/collinfo.json',{signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error(`Common Crawl ${response.status}`)}await database`UPDATE connector_configs SET last_test_status='success',last_test_message='Outbound connection validated',last_tested_at=now(),failure_count=0,circuit_open_until=null,updated_at=now() WHERE id=${id}`}catch(error){await database`UPDATE connector_configs SET last_test_status='failed',last_test_message=${String(error).slice(0,1000)},last_tested_at=now(),failure_count=failure_count+1,circuit_open_until=CASE WHEN failure_count>=4 THEN now()+interval '15 minutes' ELSE circuit_open_until END,updated_at=now() WHERE id=${id}`;throw error}}

async function discoverKeywords(database:Database,domainId:string):Promise<void>{
  const projects=await database<Array<{id:string}>>`SELECT id FROM search_projects WHERE domain_id=${domainId}`;if(!projects[0])throw new Error('Search project not found');const pages=await database<Array<Record<string,unknown>>>`SELECT p.url,p.title,p.h1,p.id FROM pages p JOIN audits a ON a.id=p.audit_id WHERE a.id=(SELECT id FROM audits WHERE domain_id=${domainId} AND status='completed' ORDER BY completed_at DESC LIMIT 1) ORDER BY p.url LIMIT 5000`;const candidates=new Map<string,{query:string;url:string;evidence:string}>();for(const page of pages){const values=[String(page.title??'').split(/[|–—:-]/)[0]??'',...((page.h1??[]) as string[]),urlPhrase(String(page.url))];for(const value of values){const query=cleanPhrase(value);if(query.length<3||query.length>120||query.split(' ').length>10)continue;const normalized=normalizeQuery(query);if(!candidates.has(normalized))candidates.set(normalized,{query,url:String(page.url),evidence:String(page.id)})}}for(const [normalized,item] of [...candidates].slice(0,1000)){await database`INSERT INTO keywords(id,search_project_id,query,normalized_query,source,source_evidence,target_url,intent,tracking_tier,status,business_priority) VALUES(${newId('keyword')},${projects[0].id},${item.query},${normalized},'site-crawl',${database.json([`page:${item.evidence}`] as never)},${item.url},${inferIntent(item.query)},'discovery','candidate',2) ON CONFLICT(search_project_id,normalized_query) DO UPDATE SET source_evidence=EXCLUDED.source_evidence,target_url=COALESCE(keywords.target_url,EXCLUDED.target_url),updated_at=now()`}}

async function runSerpBatch(database:Database,job:Job):Promise<void>{
  const domainId=String(job.payload.domainId);const connectorId=job.payload.connectorId?String(job.payload.connectorId):(await database<Array<{id:string}>>`SELECT id FROM connector_configs WHERE provider IN('dataforseo','serpapi') AND enabled=true ORDER BY CASE provider WHEN 'dataforseo' THEN 1 ELSE 2 END LIMIT 1`)[0]?.id;if(!connectorId)throw new Error('SERP connector not configured');const connector=await loadSerpConnector(database,connectorId);const tier=String(job.payload.tier??'all');const selected=Array.isArray(job.payload.keywordIds)?job.payload.keywordIds.map(String):[];const keywords=await database<Array<Record<string,unknown>>>`SELECT k.*,sp.country,sp.language,sp.location,sp.devices,d.hostname FROM keywords k JOIN search_projects sp ON sp.id=k.search_project_id JOIN domains d ON d.id=sp.domain_id WHERE sp.domain_id=${domainId} AND k.status='approved' AND k.tracking_tier<>'paused' AND (${tier}='all' OR k.tracking_tier=${tier}) AND (${selected.length===0} OR k.id=ANY(${selected})) ORDER BY k.business_priority DESC,k.updated_at LIMIT 1000`;const estimated=keywords.reduce((sum,row)=>sum+Math.max(1,((row.devices??[]) as unknown[]).length),0)*.01;await assertBudget(database,connector,estimated);
  for(const keyword of keywords){for(const device of ((keyword.devices??['mobile']) as Array<'mobile'|'desktop'>)){await captureSerp(database,connector,{keywordId:String(keyword.id),domainId,hostname:String(keyword.hostname),query:String(keyword.query),location:String(keyword.location),country:String(keyword.country),language:String(keyword.language),device,depth:Number(connector.config.depth??20)})}}
  await rebuildRankingGaps(database,domainId);await rebuildRankingOpportunities(database,domainId);
}

async function captureSerp(database:Database,connector:Awaited<ReturnType<typeof loadSerpConnector>>,input:{keywordId:string;domainId:string;hostname:string;query:string;location:string;country:string;language:string;device:'mobile'|'desktop';depth:number}):Promise<void>{
  const connectorRunId=newId('connectorRun');const serpRunId=newId('serpRun');await database`INSERT INTO connector_runs(id,connector_id,domain_id,purpose,request_context,status,estimated_cost) VALUES(${connectorRunId},${connector.id},${input.domainId},'serp_observation',${database.json(input as never)},'running',0.01)`;await database`INSERT INTO serp_runs(id,keyword_id,connector_run_id,provider,location,country,language,device,depth,status,observed_at) VALUES(${serpRunId},${input.keywordId},${connectorRunId},${connector.provider},${input.location},${input.country},${input.language},${input.device},${input.depth},'running',now())`;
  try{const result=await fetchSerp(connector,input);const rawHash=sha256(JSON.stringify(result.raw));const artifactId=newId('externalEvidence');await database`INSERT INTO external_artifacts(id,domain_id,connector_run_id,kind,sha256,payload,metadata,observed_at) VALUES(${artifactId},${input.domainId},${connectorRunId},'serp-response',${rawHash},${database.json(result.raw as never)},${database.json({provider:result.provider,query:input.query,location:input.location,language:input.language,device:input.device} as never)},${result.observedAt}) ON CONFLICT DO NOTHING`;const artifacts=await database<Array<{id:string}>>`SELECT id FROM external_artifacts WHERE domain_id=${input.domainId} AND sha256=${rawHash} AND kind='serp-response' LIMIT 1`;for(const item of result.items){await database`INSERT INTO serp_results(id,serp_run_id,result_type,rank_absolute,rank_group,domain,url,title,snippet,is_target,payload) VALUES(${newId('serpResult')},${serpRunId},${item.type},${item.rankAbsolute},${item.rankGroup},${item.domain},${item.url},${item.title},${item.snippet},${sameHost(item.domain,input.hostname)},${database.json(item.payload as never)})`;if(item.domain&&!sameHost(item.domain,input.hostname))await database`INSERT INTO competitors(id,domain_id,hostname,origin,source,status,overlap_keywords,last_seen_at) VALUES(${newId('competitor')},${input.domainId},${item.domain},${item.url?new URL(item.url).origin:null},'serp','candidate',1,${result.observedAt}) ON CONFLICT(domain_id,hostname) DO UPDATE SET overlap_keywords=competitors.overlap_keywords+1,last_seen_at=EXCLUDED.last_seen_at,updated_at=now()`}for(const feature of result.features)await database`INSERT INTO serp_features(id,serp_run_id,feature_type,owner_domain,url,rank_absolute,payload) VALUES(${newId('serpFeature')},${serpRunId},${feature.type},${feature.domain||null},${feature.url},${feature.rankAbsolute},${database.json(feature.payload as never)})`;const status=result.items.length?'success':'no-data';await database`UPDATE serp_runs SET status=${status},sample_size=${result.items.length},raw_artifact_id=${artifacts[0]?.id??null},observed_at=${result.observedAt},completed_at=now() WHERE id=${serpRunId}`;await database`UPDATE connector_runs SET status=${status},actual_cost=${result.cost},response_sha256=${rawHash},external_reference=${result.externalReference??null},completed_at=now() WHERE id=${connectorRunId}`;await database`UPDATE keywords SET last_observed_at=${result.observedAt},updated_at=now() WHERE id=${input.keywordId}`}catch(error){const limited=Boolean((error as {rateLimited?:boolean}).rateLimited);await database`UPDATE serp_runs SET status=${limited?'rate-limited':'failed'},error=${String(error).slice(0,5000)},completed_at=now() WHERE id=${serpRunId}`;await database`UPDATE connector_runs SET status=${limited?'rate-limited':'failed'},error=${String(error).slice(0,5000)},completed_at=now() WHERE id=${connectorRunId}`;throw error}}

async function refreshCompetitors(database:Database,domainId:string):Promise<void>{
  const rows=await database<Array<Record<string,unknown>>>`SELECT c.id,c.hostname,c.origin,r.url FROM competitors c LEFT JOIN LATERAL(SELECT sr.url FROM serp_results sr JOIN serp_runs run ON run.id=sr.serp_run_id JOIN keywords k ON k.id=run.keyword_id JOIN search_projects sp ON sp.id=k.search_project_id WHERE sp.domain_id=c.domain_id AND sr.domain=c.hostname AND sr.result_type='organic' ORDER BY run.observed_at DESC,sr.rank_absolute LIMIT 1) r ON true WHERE c.domain_id=${domainId} AND c.status='approved' ORDER BY c.overlap_keywords DESC LIMIT 30`;for(const row of rows){const url=String(row.url??row.origin??'');if(!url)continue;try{await validateTarget(url);if(!(await allowedByRobots(url)))throw new Error('Blocked by robots.txt');const response=await fetch(url,{headers:{'user-agent':'SiteChronicle/1.0 (+private comparative audit; read-only)'},redirect:'follow',signal:AbortSignal.timeout(30_000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const html=await response.text();const $=loadHtml(html);$('script,style,noscript,svg').remove();const text=$('main,article,body').first().text().replace(/\s+/g,' ').trim();const payload={url:response.url,title:$('title').first().text().trim(),description:$('meta[name="description"]').attr('content')??'',h1:$('h1').map((_,e)=>$(e).text().trim()).get().slice(0,20),headings:$('h2,h3').map((_,e)=>$(e).text().trim()).get().filter(Boolean).slice(0,100),schemaTypes:extractSchemaTypes($),wordCount:text.split(/\s+/).filter(Boolean).length,terms:topTerms(text)};const hash=sha256(html);const artifactId=newId('externalEvidence');await database`INSERT INTO external_artifacts(id,domain_id,kind,sha256,mime_type,payload,metadata) VALUES(${artifactId},${domainId},'competitor-page',${hash},'application/json',${database.json(payload as never)},${database.json({coverage:'single-public-page',robotsRespected:true} as never)}) ON CONFLICT DO NOTHING`;const artifacts=await database<Array<{id:string}>>`SELECT id FROM external_artifacts WHERE domain_id=${domainId} AND sha256=${hash} AND kind='competitor-page' LIMIT 1`;await database`INSERT INTO competitor_snapshots(id,competitor_id,url,status,title,description,h1,word_count,headings,schema_types,content_terms,artifact_id) VALUES(${newId('competitorSnapshot')},${String(row.id)},${response.url},'success',${payload.title},${payload.description},${database.json(payload.h1 as never)},${payload.wordCount},${database.json(payload.headings as never)},${database.json(payload.schemaTypes as never)},${database.json(payload.terms as never)},${artifacts[0]?.id??null})`}catch(error){await database`INSERT INTO competitor_snapshots(id,competitor_id,url,status,error) VALUES(${newId('competitorSnapshot')},${String(row.id)},${url},${String(error).includes('robots')?'blocked':'failed'},${String(error).slice(0,2000)})`}}
  await rebuildRankingGaps(database,domainId);
}

async function refreshPublicPerformance(database:Database,domainId:string):Promise<void>{const domains=await database<Array<Record<string,unknown>>>`SELECT id,origin FROM domains WHERE id=${domainId}`;const domain=domains[0];if(!domain)throw new Error('Domain not found');const origin=String(domain.origin);const started=Date.now();try{await validateTarget(origin);const response=await fetch(origin,{method:'GET',redirect:'manual',headers:{'user-agent':'SiteChronicle/1.0'},signal:AbortSignal.timeout(20_000)});await storeMetric(database,domainId,'availability_http_status',response.status,'status','synthetic-home-server','measured',{vantage:'home-server',method:'GET'});await storeMetric(database,domainId,'availability_response_time',Date.now()-started,'ms','synthetic-home-server','measured',{vantage:'home-server',method:'GET'})}catch(error){await storeMetric(database,domainId,'availability_response_time',null,'ms','synthetic-home-server','collection-failed',{vantage:'home-server',error:String(error)})}
  const connectors=await database<Array<Record<string,unknown>>>`SELECT * FROM connector_configs WHERE provider='crux' AND enabled=true`;const connector=connectors[0];if(!connector?.encrypted_credentials){await storeMetric(database,domainId,'crux_coverage',null,null,'crux-history','not-configured',{origin});return}const credentials=decryptCredentials(String(connector.encrypted_credentials));try{const response=await fetch(`https://chromeuxreport.googleapis.com/v1/records:queryHistoryRecord?key=${encodeURIComponent(credentials.apiKey)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({origin,formFactor:'PHONE',metrics:['largest_contentful_paint','interaction_to_next_paint','cumulative_layout_shift','first_contentful_paint','experimental_time_to_first_byte']}),signal:AbortSignal.timeout(30_000)});if(response.status===404){await storeMetric(database,domainId,'crux_coverage',null,null,'crux-history','no-public-data',{origin,formFactor:'PHONE'});return}if(!response.ok)throw new Error(`CrUX History ${response.status}`);const raw=await response.json() as Record<string,unknown>;const record=(raw.record??{}) as Record<string,unknown>;const periods=(record.collectionPeriods??[]) as Array<Record<string,unknown>>;const metrics=(record.metrics??{}) as Record<string,Record<string,unknown>>;for(const [metric,value] of Object.entries(metrics)){const p75=(value.percentiles as Record<string,unknown>|undefined)?.p75;const densities=(value.histogramTimeseries as Array<Record<string,unknown>>|undefined)?.map((item,index)=>({period:periods[index],densities:item.densities}));await storeMetric(database,domainId,metric,p75===undefined?null:Number(p75),metric.includes('layout_shift')?'score':'ms','crux-history','measured',{origin,formFactor:'PHONE',periods,densities,rollingWindowDays:28,weeklyPeriods:periods.length})}}catch(error){await storeMetric(database,domainId,'crux_coverage',null,null,'crux-history','collection-failed',{origin,error:String(error)})}}

async function refreshCommonCrawl(database:Database,domainId:string):Promise<void>{const domains=await database<Array<{hostname:string}>>`SELECT hostname FROM domains WHERE id=${domainId}`;if(!domains[0])throw new Error('Domain not found');const collections=await fetch('https://index.commoncrawl.org/collinfo.json',{signal:AbortSignal.timeout(20_000)}).then(r=>r.json()) as Array<Record<string,unknown>>;const latest=String(collections[0]?.['id']??'');if(!latest)throw new Error('No Common Crawl collection');const url=new URL(`https://index.commoncrawl.org/${latest}-index`);url.searchParams.set('url',`${domains[0].hostname}/*`);url.searchParams.set('output','json');url.searchParams.set('filter','status:200');url.searchParams.set('pageSize','200');const response=await fetch(url,{signal:AbortSignal.timeout(30_000)});if(!response.ok)throw new Error(`Common Crawl ${response.status}`);const text=await response.text();const records=text.trim().split('\n').filter(Boolean).flatMap(line=>{try{return[JSON.parse(line)]}catch{return[]}});const payload={collection:latest,hostname:domains[0].hostname,records,coverage:'Common Crawl is sampled and lagged; this is not a complete index or backlink graph.'};await database`INSERT INTO external_artifacts(id,domain_id,kind,sha256,payload,metadata) VALUES(${newId('externalEvidence')},${domainId},'commoncrawl-index',${sha256(JSON.stringify(payload))},${database.json(payload as never)},${database.json({coverage:'incomplete-public-crawl'} as never)}) ON CONFLICT DO NOTHING`;await storeMetric(database,domainId,'commoncrawl_urls',records.length,'urls','commoncrawl','measured',{collection:latest,coverage:'incomplete'})}

async function rebuildRankingGaps(database:Database,domainId:string):Promise<void>{
  await database`DELETE FROM ranking_gap_candidates WHERE domain_id=${domainId} AND status='open'`;
  const rows=await database<Array<Record<string,unknown>>>`SELECT k.id AS keyword_id,k.query,k.target_url,sr.id AS run_id,sr.observed_at,
    (SELECT min(rank_absolute) FROM serp_results WHERE serp_run_id=sr.id AND is_target=true AND result_type='organic') AS target_rank,
    (SELECT count(*) FROM serp_results WHERE serp_run_id=sr.id AND result_type='organic')::int AS sample_size,
    (SELECT jsonb_agg(jsonb_build_object('id',id,'rank',rank_absolute,'domain',domain,'url',url,'title',title) ORDER BY rank_absolute)
      FROM serp_results WHERE serp_run_id=sr.id AND result_type='organic' AND is_target=false AND rank_absolute<=5) AS top_results
    FROM keywords k JOIN search_projects sp ON sp.id=k.search_project_id
    JOIN LATERAL(SELECT * FROM serp_runs WHERE keyword_id=k.id AND status IN('success','partial') ORDER BY observed_at DESC LIMIT 1) sr ON true
    WHERE sp.domain_id=${domainId}`;
  for(const row of rows){
    const rank=row.target_rank===null?null:Number(row.target_rank);const top=(row.top_results??[]) as Array<Record<string,unknown>>;
    if(rank!==null&&rank<=3)continue;
    const serpEvidence=[`serp:${row.run_id}`,...top.map(item=>`serp-result:${item.id}`)];
    await database`INSERT INTO ranking_gap_candidates(id,domain_id,keyword_id,target_url,dimension,observation,rationale,recommendation,counterevidence,confidence,confidence_reason,sample_size,supports_evidence,counters_evidence,source_urls)
      VALUES(${newId('rankingGap')},${domainId},${String(row.keyword_id)},${row.target_url?String(row.target_url):null},'serp-visibility',
      ${rank===null?`Target domain was not observed in the captured organic result depth for “${row.query}”.`:`Target was observed at contextual rank ${rank} for “${row.query}”; the captured top results are competitors.`},
      'The SERP snapshot establishes a visibility gap in this exact location/language/device sample. It does not establish Google’s causal weighting.',
      'Compare the target page with captured top pages for intent, format, topic coverage, internal linking and technical eligibility; change only gaps supported by page evidence.',
      'A different time, user context, location or provider sample may return another order. Strong page-experience scores alone do not guarantee a higher rank.',
      ${Number(row.sample_size)>=10?'medium':'low'},${Number(row.sample_size)>=10?'At least ten organic results were captured, but repeated samples are still required.':'The captured sample is small or incomplete.'},
      ${Number(row.sample_size)},${database.json(serpEvidence as never)},${database.json([] as never)},${database.json(['https://developers.google.com/search/docs/appearance/ranking-systems-guide','https://support.google.com/websearch/answer/12412910?hl=en'] as never)})`;
    if(!row.target_url)continue;
    const targetRows=await database<Array<Record<string,unknown>>>`SELECT * FROM page_features WHERE domain_id=${domainId} AND page_url=${String(row.target_url)} ORDER BY observed_at DESC LIMIT 1`;
    const target=targetRows[0];if(!target)continue;
    const competitorHosts=top.map(item=>String(item.domain??'')).filter(Boolean);
    const comparisons=await database<Array<Record<string,unknown>>>`SELECT DISTINCT ON(c.hostname) c.hostname,s.word_count,s.schema_types,s.content_terms,s.artifact_id,s.observed_at
      FROM competitors c JOIN competitor_snapshots s ON s.competitor_id=c.id
      WHERE c.domain_id=${domainId} AND c.hostname=ANY(${competitorHosts}) AND s.status='success'
      ORDER BY c.hostname,s.observed_at DESC`;
    if(!comparisons.length)continue;
    const targetTerms=new Set(((target.topics??[]) as Array<Record<string,unknown>>).map(item=>String(item.term??item)).filter(Boolean));
    const termFrequency=new Map<string,number>();for(const comparison of comparisons)for(const term of (comparison.content_terms??[]) as string[])termFrequency.set(String(term),(termFrequency.get(String(term))??0)+1);
    const missingTerms=[...termFrequency].filter(([term,count])=>count>=Math.min(2,comparisons.length)&&!targetTerms.has(term)).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([term])=>term);
    const targetSchemas=new Set(((target.schema_types??[]) as string[]).map(String));const commonSchemas=[...new Set(comparisons.flatMap(item=>(item.schema_types??[]) as string[]))].filter(schema=>!targetSchemas.has(String(schema))).slice(0,8);
    const medianWords=[...comparisons].map(item=>Number(item.word_count??0)).sort((a,b)=>a-b)[Math.floor(comparisons.length/2)]??0;
    const differences=[missingTerms.length?`recurring competitor terms absent from the target sample: ${missingTerms.join(', ')}`:'no recurring missing topic terms in this sample',commonSchemas.length?`schema types seen only in compared pages: ${commonSchemas.join(', ')}`:'no schema-type difference',`target internal inlinks ${target.internal_inlinks??0}, crawl depth ${target.crawl_depth??'unknown'}`,`target word count ${target.word_count??0}; competitor sample median ${medianWords}`];
    const pageEvidence=[...((target.evidence_ids??[]) as string[]),...comparisons.map(item=>String(item.artifact_id)).filter(Boolean)];
    await database`INSERT INTO ranking_gap_candidates(id,domain_id,keyword_id,target_url,dimension,observation,rationale,recommendation,counterevidence,confidence,confidence_reason,sample_size,supports_evidence,counters_evidence,source_urls)
      VALUES(${newId('rankingGap')},${domainId},${String(row.keyword_id)},${String(row.target_url)},'page-comparison',${differences.join('; ')},
      'These are reproducible differences between the latest crawled target page and public pages observed above it. They are candidates for review, not ranking factors or causal proof.',
      'Verify search intent manually, address only genuinely useful missing coverage, improve internal discovery when warranted, and add structured data only when it accurately describes visible content.',
      'Longer content and more schema do not inherently improve quality or rank. Public competitor snapshots cover one page each and may be stale.',
      ${comparisons.length>=3?'medium':'low'},${`${comparisons.length} approved competitor page snapshot(s) were compared with one target crawl; repeated observations are needed.`},
      ${comparisons.length+1},${database.json([...serpEvidence,...pageEvidence] as never)},${database.json([] as never)},${database.json(['https://developers.google.com/search/docs/fundamentals/creating-helpful-content','https://developers.google.com/search/docs/appearance/structured-data/sd-policies'] as never)})`;
  }
}

async function rebuildRankingOpportunities(database:Database,domainId:string):Promise<void>{const gaps=await database<Array<Record<string,unknown>>>`SELECT g.*,k.query,k.business_priority FROM ranking_gap_candidates g JOIN keywords k ON k.id=g.keyword_id WHERE g.domain_id=${domainId} AND g.status='open' ORDER BY k.business_priority DESC,g.observed_at DESC LIMIT 100`;for(const gap of gaps){const confidence=gap.confidence==='high'?.85:gap.confidence==='medium'?.65:.4;const relevance=Number(gap.business_priority??3)/5;const priority=Math.round(35+confidence*35+relevance*30);const fingerprint=`ranking-gap:${gap.keyword_id}:${gap.dimension}`;await database`INSERT INTO opportunities(id,domain_id,fingerprint,category,title,observation,rationale,recommendation,acceptance_criteria,validation_plan,evidence_ids,source_urls,confidence,priority,effort,impact_status) VALUES(${newId('opportunity')},${domainId},${fingerprint},'search-visibility',${`Visibility gap: ${gap.query}`},${String(gap.observation)},${String(gap.rationale)},${String(gap.recommendation)},${database.json(['Capture at least three comparable SERP observations','Address only page gaps supported by stored evidence','No technical or page-experience guardrail regresses'] as never)},'Record the change, keep location/language/device constant, compare repeated before/after medians, and report traffic impact as unavailable without private analytics.',${database.json(gap.supports_evidence as never)},${database.json(gap.source_urls as never)},${confidence},${priority},'medium','site-hypothesis') ON CONFLICT(domain_id,fingerprint) DO UPDATE SET observation=EXCLUDED.observation,rationale=EXCLUDED.rationale,recommendation=EXCLUDED.recommendation,evidence_ids=EXCLUDED.evidence_ids,source_urls=EXCLUDED.source_urls,confidence=EXCLUDED.confidence,priority=EXCLUDED.priority,last_seen_at=now(),updated_at=now(),resolved_at=null,status=CASE WHEN opportunities.status='resolved' THEN 'open' ELSE opportunities.status END`;const opportunities=await database<Array<{id:string}>>`SELECT id FROM opportunities WHERE domain_id=${domainId} AND fingerprint=${fingerprint}`;if(opportunities[0])for(const evidenceId of (gap.supports_evidence??[]) as string[])await database`INSERT INTO opportunity_evidence(opportunity_id,evidence_id,role) VALUES(${opportunities[0].id},${evidenceId},'supports') ON CONFLICT DO NOTHING`}}

async function evaluateExperiment(database:Database,experimentId:string):Promise<void>{
  const rows=await database<Array<{target_keyword_ids:string[];baseline_start:string;baseline_end:string;evaluation_start:string;evaluation_end:string}>>`SELECT target_keyword_ids,baseline_start,baseline_end,evaluation_start,evaluation_end FROM experiments WHERE id=${experimentId}`;
  const exp=rows[0];if(!exp)throw new Error('Experiment not found');const target=exp.target_keyword_ids??[];
  if(!target.length){await database`UPDATE experiments SET status='inconclusive',result_summary='No target keywords were attached.',uncertainty='Traffic, clicks and revenue are unavailable without private analytics.',updated_at=now() WHERE id=${experimentId}`;return}
  const observations=await database<Array<{period:string;mean_rank:number|null;median_rank:number|null;samples:number}>>`SELECT CASE WHEN sr.observed_at BETWEEN ${exp.baseline_start} AND ${exp.baseline_end} THEN 'baseline' WHEN sr.observed_at BETWEEN ${exp.evaluation_start} AND ${exp.evaluation_end} THEN 'evaluation' ELSE NULL END AS period,avg(r.rank)::double precision AS mean_rank,percentile_cont(.5) WITHIN GROUP(ORDER BY r.rank)::double precision AS median_rank,count(r.rank)::int AS samples FROM serp_runs sr LEFT JOIN LATERAL(SELECT min(rank_absolute)::double precision AS rank FROM serp_results WHERE serp_run_id=sr.id AND is_target=true AND result_type='organic') r ON true WHERE sr.keyword_id=ANY(${target}) AND (sr.observed_at BETWEEN ${exp.baseline_start} AND ${exp.baseline_end} OR sr.observed_at BETWEEN ${exp.evaluation_start} AND ${exp.evaluation_end}) GROUP BY period`;
  for(const row of observations)await database`INSERT INTO experiment_observations(id,experiment_id,period,metric,value,sample_size,status,context,evidence_ids) VALUES(${newId('experimentObservation')},${experimentId},${row.period},'median_contextual_rank',${row.median_rank},${row.samples},${row.samples>=3?'measured':'insufficient'},${database.json({meanRank:row.mean_rank} as never)},${database.json([] as never)})`;
  const baseline=observations.find((row)=>row.period==='baseline');const evaluation=observations.find((row)=>row.period==='evaluation');let status='inconclusive',summary='Insufficient comparable observations.';
  if(Number(baseline?.samples??0)>=3&&Number(evaluation?.samples??0)>=3){const delta=Number(baseline?.median_rank)-Number(evaluation?.median_rank);status=delta>=2?'supported':delta<=-2?'regressed':'inconclusive';summary=`Contextual median rank changed from ${Number(baseline?.median_rank).toFixed(1)} to ${Number(evaluation?.median_rank).toFixed(1)} (${delta>0?'+':''}${delta.toFixed(1)} positions). This is an association around the recorded change, not proof of Google causality.`}
  await database`UPDATE experiments SET status=${status},result_summary=${summary},uncertainty='SERPs vary by context and time; competitor and algorithm changes are confounders. Traffic/click/revenue effects are unavailable.',updated_at=now() WHERE id=${experimentId}`
}

async function buildDigest(database:Database):Promise<void>{const rows=await database`SELECT d.id,d.name,(SELECT count(*)::int FROM opportunities o WHERE o.domain_id=d.id AND o.status='open') AS open_opportunities,(SELECT max(observed_at) FROM serp_runs sr JOIN keywords k ON k.id=sr.keyword_id JOIN search_projects sp ON sp.id=k.search_project_id WHERE sp.domain_id=d.id) AS last_serp,(SELECT max(completed_at) FROM audits WHERE domain_id=d.id AND status='completed') AS last_audit FROM domains d WHERE archived_at IS NULL ORDER BY d.name`;await database`INSERT INTO daily_digests(id,digest_date,payload) VALUES(${newId('digest')},current_date,${database.json({sites:rows,generatedAt:new Date().toISOString()} as never)}) ON CONFLICT(digest_date) DO UPDATE SET payload=EXCLUDED.payload,created_at=now()`}

async function storeMetric(database:Database,domainId:string,metric:string,value:number|null,unit:string|null,source:string,status:string,context:Record<string,unknown>):Promise<void>{await database`INSERT INTO public_metric_series(id,domain_id,metric,value,unit,source,measurement_context,status,observed_at) VALUES(${newId('publicMetric')},${domainId},${metric},${value},${unit},${source},${database.json(context as never)},${status},now())`}
async function allowedByRobots(value:string):Promise<boolean>{const url=new URL(value);const response=await fetch(new URL('/robots.txt',url.origin),{headers:{'user-agent':'SiteChronicle/1.0'},signal:AbortSignal.timeout(10_000)}).catch(()=>null);if(!response||!response.ok)return true;const text=await response.text();let applies=false;for(const raw of text.split(/\r?\n/)){const line=raw.replace(/#.*/,'').trim();const [name,...rest]=line.split(':');const val=rest.join(':').trim();if(name?.toLowerCase()==='user-agent')applies=val==='*'||val.toLowerCase().includes('sitechronicle');if(applies&&name?.toLowerCase()==='disallow'&&val==='/' )return false}return true}
function extractSchemaTypes($:ReturnType<typeof loadHtml>):string[]{const set=new Set<string>();$('script[type="application/ld+json"]').each((_,element)=>{try{const value=JSON.parse($(element).text());walk(value)}catch{} });function walk(value:unknown):void{if(Array.isArray(value)){value.forEach(walk);return}if(!value||typeof value!=='object')return;const row=value as Record<string,unknown>;const type=row['@type'];if(typeof type==='string')set.add(type);if(Array.isArray(type))type.forEach(v=>set.add(String(v)));Object.values(row).forEach(walk)}return[...set].slice(0,50)}
function topTerms(text:string):string[]{const stop=new Set(['the','and','for','with','this','that','from','your','bir','ile','için','ve','bu','da','de','çok','daha','olarak']);const counts=new Map<string,number>();for(const word of text.toLocaleLowerCase('tr-TR').match(/[\p{L}\p{N}]{3,}/gu)??[]){if(stop.has(word))continue;counts.set(word,(counts.get(word)??0)+1)}return[...counts].sort((a,b)=>b[1]-a[1]).slice(0,50).map(([word])=>word)}
function normalizeQuery(value:string):string{return value.normalize('NFKC').toLocaleLowerCase('tr-TR').replace(/\s+/g,' ').trim()}
function cleanPhrase(value:string):string{return value.replace(/[\n\r\t]+/g,' ').replace(/\s+/g,' ').replace(/^[\W_]+|[\W_]+$/gu,'').trim()}
function urlPhrase(value:string):string{try{const path=new URL(value).pathname.split('/').filter(Boolean).at(-1)??'';return decodeURIComponent(path).replace(/[-_]+/g,' ')}catch{return''}}
function inferIntent(value:string):string{const q=value.toLocaleLowerCase('tr-TR');if(/yakınımda|near me|istanbul|ankara|izmir/.test(q))return'local';if(/satın al|fiyat|ücret|price|buy|kirala/.test(q))return'transactional';if(/nasıl|nedir|rehber|how|what|why/.test(q))return'informational';return'unknown'}
function sameHost(a:string,b:string):boolean{const normalize=(v:string)=>v.toLowerCase().replace(/^www\./,'');return normalize(a)===normalize(b)}
