import { load } from 'cheerio';
import { createFinding, type Finding } from '@sitechronicle/core';
import type { CrawledPage } from '../crawler.js';

export interface SeoAnalysis { findings: Finding[]; metrics: Record<string,unknown> }

export function analyzeSeo(input: { auditId:string; pageId:string; page:CrawledPage; htmlEvidenceId:string }): SeoAnalysis {
  const { auditId,pageId,page,htmlEvidenceId }=input; const $=load(page.html); const findings:Finding[]=[];
  const base={auditId,pageId,pageUrl:page.finalUrl,evidenceIds:[htmlEvidenceId],sourceUrls:['https://developers.google.com/search/docs/fundamentals/seo-starter-guide']};
  const add=(data:Parameters<typeof createFinding>[0])=>findings.push(createFinding(data));
  if(page.statusCode!==200)add({...base,ruleId:'SEO-HTTP-001',category:'seo',severity:page.statusCode>=500?'critical':'high',title:`Page returned HTTP ${page.statusCode}`,observation:`The audited URL returned ${page.statusCode}.`,impactHypothesis:'Non-200 landing pages can interrupt discovery and user journeys.',impactStatus:'research-backed-hypothesis',probableCause:'The route is missing, redirected incorrectly or unavailable.',recommendation:'Return the intentional status and remove broken internal/sitemap references.',acceptanceCriteria:['Indexable landing URL returns 200','Internal and sitemap references match the final canonical URL'],confidence:1});
  if(!page.title)add({...base,ruleId:'SEO-TITLE-001',category:'seo',severity:'high',title:'Document title is empty',observation:'No non-empty <title> was found.',impactHypothesis:'Search engines and users receive a weak page-purpose signal.',impactStatus:'research-backed-hypothesis',probableCause:'The page template does not enforce a title.',recommendation:'Generate a unique, human-readable title from the page entity.',acceptanceCriteria:['Exactly one non-empty title exists','Title is unique within the audited URL set'],confidence:1});
  else if(page.title.length<15||page.title.length>65)add({...base,ruleId:'SEO-TITLE-002',category:'seo',severity:'medium',title:'Title length is outside the review range',observation:`Title contains ${page.title.length} characters.`,impactHypothesis:'The title may be vague or truncated; length alone is not a ranking rule.',impactStatus:'site-hypothesis',probableCause:'Metadata is generic or generated without editorial bounds.',recommendation:'Review query intent and write a specific title; do not optimize length in isolation.',acceptanceCriteria:['Title names the page entity and intent','SERP preview is manually reviewed'],confidence:.96,numericValue:page.title.length,numericUnit:'characters'});
  if(!page.description)add({...base,ruleId:'SEO-DESC-001',category:'seo',severity:'medium',title:'Meta description is empty',observation:'No non-empty meta description was found.',impactHypothesis:'Search snippets may have less controlled commercial messaging.',impactStatus:'research-backed-hypothesis',probableCause:'Description generation is missing for this template.',recommendation:'Add a unique, accurate summary with the primary value proposition.',acceptanceCriteria:['Description is non-empty','Description matches visible page content'],confidence:1});
  if(page.h1.length===0)add({...base,ruleId:'SEO-H1-001',category:'seo',severity:'high',title:'Visible primary heading is missing',observation:'No non-empty H1 was found.',impactHypothesis:'Page purpose and scanning hierarchy are less explicit.',impactStatus:'research-backed-hypothesis',probableCause:'Heading text is embedded in imagery or the template omits semantic markup.',recommendation:'Add one visible, descriptive H1.',acceptanceCriteria:['One primary page heading is visible','Heading describes the current entity'],confidence:1});
  if(page.h1.length>1)add({...base,ruleId:'SEO-H1-002',category:'seo',severity:'low',title:'Multiple H1 elements need hierarchy review',observation:`${page.h1.length} non-empty H1 elements were found.`,impactHypothesis:'Multiple H1s are valid HTML but often expose weak document hierarchy.',impactStatus:'site-hypothesis',probableCause:'Modal or section titles reuse the page-heading component.',recommendation:'Keep the entity title as H1 and demote supporting/modal headings.',acceptanceCriteria:['Heading outline is logical','Modal titles do not impersonate the page title'],confidence:.95,numericValue:page.h1.length,numericUnit:'elements'});
  if(!page.canonical)add({...base,ruleId:'SEO-CANON-001',category:'seo',severity:'medium',title:'Canonical is missing',observation:'No canonical link was found.',impactHypothesis:'Duplicate URL consolidation is left entirely to search engines.',impactStatus:'research-backed-hypothesis',probableCause:'Canonical is absent from the shared head template.',recommendation:'Publish one absolute normalized canonical URL.',acceptanceCriteria:['Canonical is absolute','Canonical resolves to 200 and is indexable'],confidence:1});
  else if(page.canonical!==page.normalizedUrl)add({...base,ruleId:'SEO-CANON-002',category:'seo',severity:'medium',title:'Canonical points away from the audited URL',observation:`Canonical is ${page.canonical}; normalized page URL is ${page.normalizedUrl}.`,impactHypothesis:'The page may be consolidated elsewhere intentionally or by mistake.',impactStatus:'site-hypothesis',probableCause:'Template, pagination or parameter canonical logic differs.',recommendation:'Verify intent; indexable unique pages should generally self-canonicalize.',acceptanceCriteria:['Canonical strategy is documented','Canonical target is equivalent and indexable'],confidence:1});
  if(/noindex/i.test(page.robots))add({...base,ruleId:'SEO-ROBOTS-001',category:'seo',severity:page.template==='product'||page.template==='category'?'high':'info',title:'Page declares noindex',observation:`Robots meta is “${page.robots}”.`,impactHypothesis:'The URL is not intended for search indexing.',impactStatus:'informational',probableCause:'Template or page-level indexing policy.',recommendation:'Confirm noindex matches page purpose and exclude it from XML sitemaps.',acceptanceCriteria:['Noindex URLs are absent from sitemaps','Commercial landing pages are noindex only by explicit decision'],confidence:1});
  const images=$('img');let missingAlt=0;images.each((_,el)=>{if($(el).attr('alt')===undefined)missingAlt+=1});
  if(missingAlt)add({...base,ruleId:'SEO-IMG-001',category:'seo',severity:'medium',title:'Images are missing alt attributes',observation:`${missingAlt} of ${images.length} images have no alt attribute.`,impactHypothesis:'Meaningful images may be less understandable to assistive technology and image search.',impactStatus:'research-backed-hypothesis',probableCause:'Image components do not require alt or decorative state.',recommendation:'Require descriptive alt for meaningful media and alt="" for decorative media.',acceptanceCriteria:['No image lacks the alt attribute','Decorative and meaningful images are distinguished'],confidence:1,numericValue:missingAlt,numericUnit:'images'});
  const jsonLdTypes:string[]=[];$('script[type="application/ld+json"]').each((_,el)=>{try{const value=JSON.parse($(el).text()) as unknown;collectTypes(value,jsonLdTypes)}catch{/* separately counted */}});
  if(page.template==='product'&&!jsonLdTypes.some(type=>['Product','ProductGroup'].includes(type)))add({...base,ruleId:'SEO-PRODUCT-001',category:'seo',severity:'high',title:'Product structured data is missing',observation:'No Product or ProductGroup JSON-LD type was found on the product-like URL.',impactHypothesis:'Product facts are less machine-readable for search, merchant and agent systems.',impactStatus:'research-backed-hypothesis',probableCause:'Catalog entities are rendered only as visual HTML or client data.',recommendation:'Generate ProductGroup/Product/Offer from the same price and stock source as the page.',acceptanceCriteria:['Visible price and stock equal JSON-LD values','Structured data validates without critical errors'],confidence:.91,sourceUrls:['https://developers.google.com/search/docs/appearance/structured-data/product']});
  const ogMissing=['og:title','og:description','og:image'].filter(property=>!$(`meta[property="${property}"]`).attr('content'));
  if(ogMissing.length)add({...base,ruleId:'SEO-OG-001',category:'seo',severity:'low',title:'Social preview metadata is incomplete',observation:`Missing or empty: ${ogMissing.join(', ')}.`,impactHypothesis:'Shared links may have weak or inconsistent previews.',impactStatus:'site-hypothesis',probableCause:'Open Graph fields are not enforced by the template.',recommendation:'Provide accurate title, description, absolute image and URL.',acceptanceCriteria:['Required Open Graph fields are non-empty','Preview image is fetchable and representative'],confidence:1});
  if(['account','checkout','cart','search'].includes(page.template)&&!/noindex/i.test(page.robots))add({...base,ruleId:'SEO-UTILITY-001',category:'seo',severity:'medium',title:'Utility page is indexable',observation:`${page.template} page does not declare noindex.`,impactHypothesis:'Low-value/private workflow URLs may consume index attention.',impactStatus:'research-backed-hypothesis',probableCause:'Utility templates inherit indexable defaults.',recommendation:'Apply noindex,follow where public search landing value does not exist.',acceptanceCriteria:['Utility URL has noindex','Utility URL is absent from XML sitemap'],confidence:.9});
  return {findings,metrics:{titleLength:page.title.length,descriptionLength:page.description.length,h1Count:page.h1.length,imageCount:images.length,missingAlt,jsonLdTypes,ogMissing}};
}
function collectTypes(value:unknown,out:string[]):void{if(Array.isArray(value)){for(const item of value)collectTypes(item,out);return}if(!value||typeof value!=='object')return;const record=value as Record<string,unknown>;const type=record['@type'];if(typeof type==='string')out.push(type);else if(Array.isArray(type))out.push(...type.filter((item):item is string=>typeof item==='string'));if(record['@graph'])collectTypes(record['@graph'],out)}
