import { load } from 'cheerio';
import { createFinding, type Finding } from '@sitechronicle/core';
import type { CrawledPage } from '../crawler.js';

export function analyzeSitewide(input:{auditId:string;pages:Array<{page:CrawledPage;evidenceId:string}>;robotsEvidenceId:string;sitemapEvidenceIds:string[]}):{findings:Finding[];agentScore:number;facts:Record<string,unknown>} {
  const findings:Finding[]=[];const phones=new Map<string,Set<string>>();const emails=new Map<string,Set<string>>();let productPages=0;let productSchema=0;let organizationSchema=0;
  for(const item of input.pages){const text=load(item.page.html).text().replace(/\s+/g,' ');for(const raw of text.match(/(?:\+?90\s*)?(?:0\s*)?5\d{2}[\s().-]*\d{3}[\s.-]*\d{2}[\s.-]*\d{2}/g)??[]){const value=raw.replace(/\D/g,'').replace(/^90/,'').replace(/^0/,'');if(value.length===10){if(!phones.has(value))phones.set(value,new Set());phones.get(value)!.add(item.page.finalUrl)}}for(const email of text.match(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi)??[]){const value=email.toLowerCase();if(!emails.has(value))emails.set(value,new Set());emails.get(value)!.add(item.page.finalUrl)}const types=jsonLdTypes(item.page.html);if(types.includes('Organization')||types.includes('LocalBusiness'))organizationSchema+=1;if(item.page.template==='product'){productPages+=1;if(types.includes('Product')||types.includes('ProductGroup'))productSchema+=1}}
  const baseEvidence=[input.robotsEvidenceId,...input.sitemapEvidenceIds,...input.pages.slice(0,8).map(item=>item.evidenceId)].filter(Boolean);
  if(phones.size>1)findings.push(createFinding({auditId:input.auditId,ruleId:'TRUST-PHONE-001',category:'behavioral-ux',severity:'high',title:'Multiple customer-facing phone facts require reconciliation',observation:`${phones.size} distinct mobile phone values were extracted across audited pages.`,impactHypothesis:'Conflicting contact facts can increase perceived transaction risk and produce inconsistent agent answers.',impactStatus:'research-backed-hypothesis',probableCause:'Contact, policy and structured-data content are maintained in separate sources.',recommendation:'Create one versioned commerce-facts source and render HTML/schema/help content from it.',acceptanceCriteria:['Approved support phone is consistent across surfaces','Intentional sales/support numbers are explicitly labeled'],evidenceIds:baseEvidence,sourceUrls:['https://doi.org/10.1080/10864415.2003.11044275'],confidence:.88,numericValue:phones.size,numericUnit:'distinct phones'}));
  if(productPages&&productSchema<productPages)findings.push(createFinding({auditId:input.auditId,ruleId:'AGENT-PRODUCT-COVERAGE-001',category:'agent-readiness',severity:'high',title:'Product entity coverage is incomplete',observation:`${productSchema} of ${productPages} crawled product-like pages expose Product/ProductGroup JSON-LD.`,impactHypothesis:'Search, merchant and AI systems receive incomplete machine-readable product facts.',impactStatus:'research-backed-hypothesis',probableCause:'Product templates do not consistently generate catalog structured data.',recommendation:'Render ProductGroup/Product/Offer from the authoritative catalog service on every indexable PDP.',acceptanceCriteria:['Eligible PDP structured-data coverage is 100%','Price, stock and identifiers match visible HTML and feed'],evidenceIds:baseEvidence,sourceUrls:['https://developers.google.com/search/docs/appearance/structured-data/product'],confidence:.96,numericValue:productPages?productSchema/productPages:0,numericUnit:'coverage ratio'}));
  if(!organizationSchema)findings.push(createFinding({auditId:input.auditId,ruleId:'AGENT-ORG-001',category:'agent-readiness',severity:'medium',title:'Organization entity is not established in sampled pages',observation:'No Organization or LocalBusiness JSON-LD type was detected.',impactHypothesis:'Machine consumers have fewer explicit identity and contact facts.',impactStatus:'research-backed-hypothesis',probableCause:'The shared site template lacks an organization entity.',recommendation:'Publish a consistent Organization entity with legal name, URL, logo, contact and sameAs.',acceptanceCriteria:['Organization schema validates','Schema facts match visible contact and policy content'],evidenceIds:baseEvidence,sourceUrls:['https://developers.google.com/search/docs/appearance/structured-data/organization'],confidence:.9}));
  const schemaCoverage=productPages?productSchema/productPages:1;const agentScore=Math.max(0,Math.round(100-(1-schemaCoverage)*55-(organizationSchema?0:20)-(phones.size>1?15:0)));
  return{findings,agentScore,facts:{phones:Object.fromEntries([...phones].map(([k,v])=>[k,[...v]])),emails:Object.fromEntries([...emails].map(([k,v])=>[k,[...v]])),productPages,productSchema,organizationSchema}};
}
function jsonLdTypes(html:string):string[]{const $=load(html);const out:string[]=[];$('script[type="application/ld+json"]').each((_,el)=>{try{walk(JSON.parse($(el).text()),out)}catch{}});return out}function walk(value:unknown,out:string[]):void{if(Array.isArray(value)){value.forEach(item=>walk(item,out));return}if(!value||typeof value!=='object')return;const r=value as Record<string,unknown>;const t=r['@type'];if(typeof t==='string')out.push(t);else if(Array.isArray(t))out.push(...t.filter((i):i is string=>typeof i==='string'));if(r['@graph'])walk(r['@graph'],out)}
